//GET_ORDER
export const  GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const  GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const  GET_ORDER_FAIL = 'GET_ORDER_FAIL'
export const  GET_ORDER_RESET = 'GET_ORDER_RESET'
