//REGISTER
export const  REGISTER_REQUEST = 'REGISTER_REQUEST'
export const  REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const  REGISTER_FAIL = 'REGISTER_FAIL'
export const  REGISTER_RESET = 'REGISTER_RESET'
