//OTP_VERIFICATION
export const  OTP_VERIFICATION_REQUEST = 'OTP_VERIFICATION_REQUEST'
export const  OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS'
export const  OTP_VERIFICATION_FAIL = 'OTP_VERIFICATION_FAIL'
export const  OTP_VERIFICATION_RESET = 'OTP_VERIFICATION_RESET'
